version: "3.3"

services:
  traefic:
    image: traefik
    restart: always
    container_name: "traefik"
    env_file: .env
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.websecure.http.tls.certResolver=letsencrypt"
      - "--entrypoints.websecure.http.tls.domains[0].main=${DOMAIN}"
      - "--entrypoints.websecure.http.tls.domains[0].sans=*.${DOMAIN}"
    ports:
      - 8080:8080
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt

  explorer:
    image: "expedition"
    container_name: "explorer"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.explorer.service=explorer"
      - "traefik.http.routers.explorer.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.explorer.middlewares=explorer-middlewares"
      - "traefik.http.middlewares.explorer-middlewares.stripprefix.prefixes=/explorer"
      - "traefik.http.routers.explorer.entrypoints=websecure"
      - "traefik.http.routers.explorer.tls.certresolver=myresolver"
      - "traefik.http.services.explorer.loadbalancer.server.port=80"