FROM ghcr.io/foundry-rs/foundry:nightly AS source

FROM debian:stable
RUN apt-get update && apt-get install -y \
  tcpflow \
  && rm -rf /var/lib/apt/lists/*
COPY --from=source /usr/local/bin/anvil /usr/bin/anvil

CMD ["anvil"]