name: Hardhat Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  REPOSITORY: ghcr.io/feshchenkod/hardhat-docker/
  IMAGE_TAG: ghcr.io/feshchenkod/hardhat

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${ }}

      - name: check path
        run: ls -l

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        working-directory: ./docker/
        with:
          context: Dockerfile.hardhat
          push: true
          tags: ${{ env.IMAGE_TAG }}:${{ github.sha }},${{ env.IMAGE_TAG }}:latest
          labels: ${{ steps.meta.outputs.labels }}
          secrets: "github_token=${{ secrets.GITHUB_TOKEN }}"

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}